Rename		RemoteClass::CUserClass			RemoteClass.CUserClass
Rename		Zero::String					string
Rename		Zero::CDictionary<Int32,Int32>	Dictionary<Int32, Int32>

namespace Rmi 0
{
	// 에코서버 예제
	request_Echo(RemoteClass::CUserClass testClass, Zero::CDictionary<Int32,Int32> dic_test, Zero::String msg);
	reponse_Echo(RemoteClass::CUserClass testClass, Zero::CDictionary<Int32, Int32> dic_test, Zero::String msg);
}