Rename		RemoteClass::CUserClass			RemoteClass.CUserClass
Rename		Zero::String					string
Rename		Zero::CDictionary<Int32,Int32>	Dictionary<Int32, Int32>
Rename		Zero::NetAddress				ZNet.NetAddress

namespace Rmi 0
{
	request_message(RemoteClass::CUserClass testClass, Zero::CDictionary<Int32,Int32> dic_test, Zero::String msg);
	reponse_message(RemoteClass::CUserClass testClass, Zero::CDictionary<Int32, Int32> dic_test, Zero::String msg);
}