namespace Rmi 0
{
	// 로비목록 요청
	request_lobby_list();

	// 로비목록 전달
	notify_lobby_list(Dictionary<ZNet.RemoteID, ZNet.MasterInfo> lobby_list);

	// 메세지 전달
	Chat(string msg);

	// 로그인 -> 로비서버로 이동
	request_go_lobby(string lobbyname);

	// 방만들기 (로비 -> 룸)
	request_make_room(string name);

	// 방입장하기 (로비 -> 룸)
	request_join_room(Guid roomID);

	// 방나가기 (룸 -> 로비)
	request_out_room();


	// --- 서버간 패킷 ---

	// 방생성
	room_lobby_makeroom(Guid roomID, string name, int number, ZNet.RemoteID remote_svr, ZNet.RemoteID remote_lobby, Guid userID);

	// 방입장
	room_lobby_joinroom(Guid roomID, Guid userID);

	// 방퇴장
	room_lobby_outroom(Guid roomID, Guid userID);
}